# Generated by Django 6.0.2 on 2026-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_primarysetting_customuser_dob_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='primarysetting',
            name='sent_activation_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='dob_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='DOB ID'),
        ),
    ]
