# Generated by Django 6.0.2 on 2026-02-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_primarysetting_sent_activation_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='primarysetting',
            old_name='sent_activation_email',
            new_name='send_activation_email',
        ),
    ]
