# Generated by Django 6.0.2 on 2026-02-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_sent_activation_email_primarysetting_send_activation_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_approved',
        ),
    ]
