# Generated by Django 6.0.2 on 2026-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=10),
        ),
    ]
