# Generated by Django 6.0.2 on 2026-02-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_department_options_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarysetting',
            name='send_activation_email',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('USER', 'User')], default='USER', max_length=10),
        ),
    ]
