"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from environ import Env

env = Env()
Env.read_env()

ENVIRONMENT=env('ENVIRONMENT')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
if ENVIRONMENT == 'development':
    DEBUG = True
    ALLOWED_HOSTS = ['*']
else:
    DEBUG = False
    ALLOWED_HOSTS = ['task.dobltd.com',]
    


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'users',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
STATIC_ROOT = BASE_DIR/'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'
STATICFILES_DIRS = [BASE_DIR/'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTH_USER_MODEL = 'users.CustomUser'

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_CONTENT_TYPE_NOSNIFF = True
    CSRF_TRUSTED_ORIGINS = ['https://choice-alien-saved.ngrok-free.app', 'https://task.dobltd.com']
else:
    CSRF_TRUSTED_ORIGINS = ["https://choice-alien-saved.ngrok-free.app",]
    
# Email settings
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'





JAZZMIN_SETTINGS = {
    "site_title": "DOB Task Manager",
    "site_header": "DOB Task Manager",
    "site_brand": "DOB Task Manager",
    "site_logo": "img/logo.png",
    "welcome_sign": "Welcome to the DOB Task Manager.",
    "copyright": "DOB Task Manager",

    "order_with_respect_to": ["users", "tasks"],
    "icons": {
        "users.CustomUser": "fas fa-user",
        "tasks.Task": "fas fa-tasks",
        "users.primarysetting": "fas fa-cogs",
        "users.department": "fas fa-building",
    },

    "hide_models": ["tasks.Task"],

    "custom_css": "admin/custom.css",
    "custom_js": "admin/custom.js",

    "changeform_format": "horizontal_tabs",
    "custom_links": {
        "Task Dashboard": [
            {
                "name": "Pending Task",
                "url": "/admin/tasks/task/?status__exact=PENDING",
                "icon": "fa-solid fa-hourglass",
                "permissions": [],
            },
            {
                "name": "In Progress",
                "url": "/admin/tasks/task/?status__exact=IN_PROGRESS",
                "icon": "fa-solid fa-sync-alt",
                "permissions": [],
            },
            {
                "name": "Review Task",
                "url": "/admin/tasks/task/?status__exact=REVIEW",
                "icon": "fa-solid fa-eye",
                "permissions": [],
            },
            {
                "name": "Completed Task",
                "url": "/admin/tasks/task/?status__exact=COMPLETED",
                "icon": "fa-regular fa-circle-check",
                "permissions": [],
            },
            {
                "name": "Blocked Task",
                "url": "/admin/tasks/task/?status__exact=BLOCKED",
                "icon": "fa-solid fa-ban",
                "permissions": [],
            },
            {
                "name": "Send Reminders",
                "url": "/admin-action/send-reminders/",
                "icon": "fa-solid fa-envelope",
                "permissions": ["auth.view_user"],
            }
        ]
    },
    "show_ui_builder": True,
}






# LOGGING = {
#     'version': 1,
#     'handlers': {
#         'file': {
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'filename': 'debug.log',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#     },
# }




