# Generated by Django 6.0.2 on 2026-02-20 06:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_assigned_by_task_status_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
