# Generated by Django 6.0.2 on 2026-02-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_status_4a0a95_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='tasks_task_priorit_a900d4_idx',
        ),
    ]
