# Generated by Django 6.0.2 on 2026-02-20 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
    ]
