# Generated by Django 6.0.2 on 2026-02-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status_updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
